apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-access-key-organizer
  labels:
    app: access-key-organizer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: access-key-organizer
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: access-key-organizer
    spec:
      containers:
        - name: access-key-organizer
          image: docker.io/noilimrev/iam-access-key-organizer:latest
          ports:
            - containerPort: 80
              protocol: TCP
