apiVersion: v1
kind: Secret
metadata:
  name: iam-access-key-organizer-secret
  labels:
    app: access-key-organizer
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
  AWS_DEFAULT_REGION: <AWS_DEFAULT_REGION>
