apiVersion: v1
kind: Service
metadata:
  name: iam-access-key-organizer-svc
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: access-key-organizer
